[package]
name = "flatbox_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
as-any = "0.3.1"
atomic_refcell = "0.1.12"
parking_lot = "0.12.1"
serde = { version = "1.0.188", features = ["derive"] }