[package]
name = "flatbox_render"
version = "0.1.0"
edition = "2021"

[dependencies]
casey = "0.4.0"
gl = "0.14.0"
glutin = { version = "0.29.1", optional = true}
image = "0.24.5"
thiserror = "1.0.49"

[features]
default = ["context"]

context = ["dep:glutin"]