[package]
name = "flatbox_core"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.4"
log = { version = "0.4.20", features = ["std"] }
nalgebra-glm = { version = "0.18.0", features = ["serde-serialize"]}